// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset(
  'package:tor_ffi_plugin/tor_ffi_plugin_bindings_generated.dart',
)
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Void>)>()
external bool tor_client_bootstrap(ffi.Pointer<ffi.Void> client);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Bool)>()
external void tor_client_set_dormant(
  ffi.Pointer<ffi.Void> client,
  bool soft_mode,
);

@ffi.Native<ffi.Uint64 Function()>()
external int tor_get_nofile_limit();

@ffi.Native<ffi.Void Function()>()
external void tor_hello();

@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> tor_last_error_message();

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void tor_proxy_stop(ffi.Pointer<ffi.Void> proxy);

@ffi.Native<ffi.Uint64 Function(ffi.Uint64)>()
external int tor_set_nofile_limit(int limit);

@ffi.Native<
    Tor Function(ffi.Uint16, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)>()
external Tor tor_start(
  int socks_port,
  ffi.Pointer<ffi.Char> state_dir,
  ffi.Pointer<ffi.Char> cache_dir,
);

final class Tor extends ffi.Struct {
  external ffi.Pointer<ffi.Void> client;

  external ffi.Pointer<ffi.Void> proxy;

  static ffi.Pointer<Tor> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Void> client,
    required ffi.Pointer<ffi.Void> proxy,
  }) =>
      $allocator<Tor>()
        ..ref.client = client
        ..ref.proxy = proxy;
}
