// ignore_for_file: always_specify_types
// ignore_for_file: camel_case_types
// ignore_for_file: non_constant_identifier_names

// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import, unused_element, deprecated_member_use_from_same_package
@ffi.DefaultAsset(
  'package:tor_ffi_plugin/tor_ffi_plugin_bindings_generated.dart',
)
library;

import 'dart:ffi' as ffi;

/// Ensure the client has bootstrapped.
///
/// # Safety
/// `client` must be a live, non-null handle returned by [`tor_start`].
/// It must not be freed while this call is in progress.
@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Void>)>()
external bool tor_client_bootstrap(ffi.Pointer<ffi.Void> client);

/// Release the client handle returned by [`tor_start`].
///
/// This shuts down the client's background tasks and closes its state and
/// cache files, which can block for a few seconds. Stop the proxy first: it
/// keeps its own reference to the client, but cannot serve connections once
/// the client is freed.
///
/// # Safety
/// `client` must be null or a live handle returned by [`tor_start`].
/// No other call may use the handle concurrently with or after this call.
/// It must not be called from within an async runtime.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void tor_client_free(ffi.Pointer<ffi.Void> client);

/// Change the client's dormant mode.
///
/// # Safety
/// `client` must be a live, non-null handle returned by [`tor_start`].
/// It must not be freed while this call is in progress.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Bool)>()
external void tor_client_set_dormant(
  ffi.Pointer<ffi.Void> client,
  bool soft_mode,
);

/// Read the current open-file limit.
///
/// # Safety
/// This function has no additional safety requirements.
@ffi.Native<ffi.Uint64 Function()>()
external int tor_get_nofile_limit();

/// Print a greeting to verify that the library is linked.
///
/// # Safety
/// This function has no additional safety requirements.
@ffi.Native<ffi.Void Function()>()
external void tor_hello();

/// Take the current thread's last error as a newly allocated C string.
///
/// # Safety
/// This function has no preconditions. The returned string is owned by the
/// caller and must be released exactly once with [`tor_string_free`].
@ffi.Native<ffi.Pointer<ffi.Char> Function()>()
external ffi.Pointer<ffi.Char> tor_last_error_message();

/// Stop the proxy and release its handle. Null is accepted.
///
/// # Safety
/// `proxy` must be null or a live proxy handle returned by [`tor_start`].
/// A non-null handle must be passed to this function only once.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>()
external void tor_proxy_stop(ffi.Pointer<ffi.Void> proxy);

/// Increase the open-file limit, up to the hard limit.
///
/// # Safety
/// This function has no additional safety requirements.
@ffi.Native<ffi.Uint64 Function(ffi.Uint64)>()
external int tor_set_nofile_limit(int limit);

/// Start a bootstrapped Tor client and a localhost SOCKS proxy.
///
/// # Safety
/// `state_dir` and `cache_dir` must point to valid, NUL-terminated strings
/// for the duration of the call. Each returned non-null handle must be
/// released exactly once with its corresponding cleanup function.
@ffi.Native<
  Tor Function(ffi.Uint16, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Char>)
>()
external Tor tor_start(
  int socks_port,
  ffi.Pointer<ffi.Char> state_dir,
  ffi.Pointer<ffi.Char> cache_dir,
);

/// Release a string returned by [`tor_last_error_message`].
///
/// # Safety
/// `message` must be null or a pointer returned by `tor_last_error_message`
/// that has not been released yet. It must not be used after this call.
@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Char>)>()
external void tor_string_free(ffi.Pointer<ffi.Char> message);

final class Tor extends ffi.Struct {
  external ffi.Pointer<ffi.Void> client;

  external ffi.Pointer<ffi.Void> proxy;

  static ffi.Pointer<Tor> $allocate(
    ffi.Allocator $allocator, {
    required ffi.Pointer<ffi.Void> client,
    required ffi.Pointer<ffi.Void> proxy,
  }) => $allocator<Tor>()
    ..ref.client = client
    ..ref.proxy = proxy;
}
