# SPDX-FileCopyrightText: 2022 Foundation Devices Inc.
#
# SPDX-License-Identifier: GPL-3.0-or-later

name: Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: REUSE Compliance Check
        uses: fsfe/reuse-action@v1

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.16.3'

      - name: Install dependencies
        run: flutter pub get

      - name: Verify Dart formatting
        run: dart format --output=none --set-exit-if-changed .

      - name: Verify Rust formatting
        run: cargo fmt --manifest-path rust/Cargo.toml --all -- --check

      - name: Run Rust tests
        run: cargo test --manifest-path rust/Cargo.toml

      - name: Analyze Dart project source
        run: flutter analyze

#      - name: Run Dart tests
#        run: flutter test
